# .github/workflows/build-index.yml
name: Build docs index

on:
  push:
    paths:
      - 'docs/**.html'
      - '.github/workflows/build-index.yml'

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate index.json
        run: |
          cd docs
          echo '[' > index.json
          find . -type f -name "*.html" ! -name "index.html" | sort | sed 's|^\./||' | jq -R . | paste -sd, - >> index.json
          echo ']' >> index.json
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/index.json
          git commit -m "Update docs/index.json" || echo "No changes"
          git push
